### ISSUE TITLE
install in yesterday's jbrowse hosed my install 

### ISSUE THREAD

**Issue by malcook** [bhofmei/jbplugin-motifdens#2]
Hi - not sure if this should be reported here

Or here: https://github.com/GMOD/jbrowse/issues/1025

Thanks for motifdens.  Looking forward to getting it working.  I am hosting yeast proteome in Jbrowse and have some AA patterns whose density I hope to easily visualize with this.

**Comment by bhofmei** [comment]
The plugin is quite slow since it’s doing extensive calculations so it definitely sits in the “loading” state for awhile.

I’m on vacation for a few more days but I’ll check into when I get back.

Brigitte

**Comment by cmdcolin** [comment]
I think the domReady is what was causing issues with jbrowse 1.13. The webpack build basically doesn't use domReady at all anymore and it gets filtered out but it didnt filter it out since it was in middle of the dependency list.

@malcook  If you want, you can manually remove domReady from that list of dependencies and it should work again, maybe that can be incorporated into the code eventually

**Comment by cmdcolin** [comment]
Specifically in the file js/View/Dialog/MotifDensityDialog.js

**Comment by bhofmei** [comment]
I've removed that dependency. It should work now (I can't get 1.13.0 to work at all to test this for myself).

**Comment by rbuels** [comment]
@malcook do you have any console errors displayed?  Is the problematic JBrowse online somewhere that I can see it?

**Comment by rbuels** [comment]
@malcook or alternatively could you just zip or tar up the whole thing, with data, and put it somewhere I can download it?

**Comment by malcook** [comment]
@rbuels - thanks for your offer of help on this.  


This is not urgent at all for me as I have since discovered alternate way of meeting my motif density visualization needs.  They are currently quite simple, being limited to making a few selected AA residues stand out, which I accomplished with creation of a new custom proteinColoringScheme in css/protein.css.


**EDIT: IGNORE THE BELOW - IT IS UNRELATED ISSUE APPARENTLY RELATED TO NOT HVAING INDEXED ANY NAMES YET**

But, yes, to your question, there is console error  -  screen snapshot is below and full log below that.

(I am working behind firewall - I could tar/zip it up but I bet you figure this out looking at the log - let me know!).

![image](https://user-images.githubusercontent.com/484282/37847543-25a57b5c-2e9f-11e8-9fee-1463cd72d56c.png)


13:35:07.526 main.js:22 MotifDensityPlugin plugin starting - v2.1.0
13:35:07.658 xhr.js:267 GET http://beta.sgc.loc:3000/data/names/root.json 404 (Not Found)
xhr @ xhr.js:267
Array.concat.dojo.xhr @ xhr.js:615
Array.concat.dojo.xhrGet @ xhr.js:643
constructor @ LazyTrie.js:66
(anonymous) @ declare.js:473
(anonymous) @ Browser.js:624
_milestoneFunction @ Browser.js:1992
loadNames @ Browser.js:598
(anonymous) @ Browser.js:178
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:328
notify @ Deferred.js:187
complete @ Deferred.js:168
resolve.callback @ Deferred.js:248
addResult @ DeferredList.js:54
(anonymous) @ DeferredList.js:37
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:358
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:589
finish @ lazyload.js:111
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
finish @ lazyload.js:113
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
css @ lazyload.js:365
_loadCSS @ Browser.js:589
(anonymous) @ Browser.js:352
forEach @ array.js:247
(anonymous) @ Browser.js:333
(anonymous) @ lang.js:385
contextRequire @ bootstrap 6bd6a93646d3ea06d82a:264
req @ bootstrap 6bd6a93646d3ea06d82a:158
(anonymous) @ Browser.js:330
_milestoneFunction @ Browser.js:1992
initPlugins @ Browser.js:276
(anonymous) @ Browser.js:177
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:2074
(anonymous) @ lang.js:385
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:68
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
signalListener @ Deferred.js:45
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:88
onLoad @ xhr.js:123
XMLHttpRequest.send (async)
xhr @ xhr.js:267
load @ JB_json_v1.js:45
(anonymous) @ ConfigManager.js:178
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:170
(anonymous) @ ConfigManager.js:146
map @ array.js:289
_loadRecur @ ConfigManager.js:144
_loadIncludes @ ConfigManager.js:163
(anonymous) @ ConfigManager.js:62
getFinalConfig @ ConfigManager.js:78
(anonymous) @ Browser.js:2051
_milestoneFunction @ Browser.js:1992
loadConfig @ Browser.js:2049
(anonymous) @ Browser.js:168
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
13:35:07.660 xhr.js:440 ErrorCtor {message: "Unable to load data/names/root.json status: 404", response: {…}, status: 404, responseText: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta char… GET /data/names/root.json</pre>↵</body>↵</html>↵", xhr: XMLHttpRequest, …}message: "Unable to load data/names/root.json status: 404"response: {url: "data/names/root.json", options: TMP, getHeader: ƒ, xhr: XMLHttpRequest, loaded: 159, …}responseText: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta charset="utf-8">↵<title>Error</title>↵</head>↵<body>↵<pre>Cannot GET /data/names/root.json</pre>↵</body>↵</html>↵"status: 404xhr: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}stack: "Error: Unable to load data/names/root.json status: 404↵    at new ErrorCtor (http://beta.sgc.loc:3000/dist/0.bundle.js:59597:21)↵    at Deferred.handleResponse (http://beta.sgc.loc:3000/dist/0.bundle.js:5107:14)↵    at XMLHttpRequest.onLoad (http://beta.sgc.loc:3000/dist/0.bundle.js:5136:9)"__proto__: Error
_deferError @ xhr.js:440
(anonymous) @ xhr.js:400
notify @ Deferred.js:187
complete @ Deferred.js:168
reject.errback @ Deferred.js:263
notify @ Deferred.js:202
complete @ Deferred.js:168
reject.errback @ Deferred.js:263
notify @ Deferred.js:202
complete @ Deferred.js:168
reject.errback @ Deferred.js:263
(anonymous) @ xhr.js:635
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.reject.reject @ Deferred.js:219
signalDeferred @ Deferred.js:84
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.reject.reject @ Deferred.js:219
signalDeferred @ Deferred.js:84
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.reject.reject @ Deferred.js:219
signalDeferred @ Deferred.js:84
signalListener @ Deferred.js:55
signalWaiting @ Deferred.js:28
Deferred.reject.reject @ Deferred.js:219
signalDeferred @ Deferred.js:84
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.reject.reject @ Deferred.js:219
handleResponse @ xhr.js:95
onLoad @ xhr.js:123
XMLHttpRequest.send (async)
xhr @ xhr.js:267
Array.concat.dojo.xhr @ xhr.js:615
Array.concat.dojo.xhrGet @ xhr.js:643
constructor @ LazyTrie.js:66
(anonymous) @ declare.js:473
(anonymous) @ Browser.js:624
_milestoneFunction @ Browser.js:1992
loadNames @ Browser.js:598
(anonymous) @ Browser.js:178
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:328
notify @ Deferred.js:187
complete @ Deferred.js:168
resolve.callback @ Deferred.js:248
addResult @ DeferredList.js:54
(anonymous) @ DeferredList.js:37
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:358
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:589
finish @ lazyload.js:111
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
finish @ lazyload.js:113
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
css @ lazyload.js:365
_loadCSS @ Browser.js:589
(anonymous) @ Browser.js:352
forEach @ array.js:247
(anonymous) @ Browser.js:333
(anonymous) @ lang.js:385
contextRequire @ bootstrap 6bd6a93646d3ea06d82a:264
req @ bootstrap 6bd6a93646d3ea06d82a:158
(anonymous) @ Browser.js:330
_milestoneFunction @ Browser.js:1992
initPlugins @ Browser.js:276
(anonymous) @ Browser.js:177
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:2074
(anonymous) @ lang.js:385
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:68
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
signalListener @ Deferred.js:45
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:88
onLoad @ xhr.js:123
XMLHttpRequest.send (async)
xhr @ xhr.js:267
load @ JB_json_v1.js:45
(anonymous) @ ConfigManager.js:178
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:170
(anonymous) @ ConfigManager.js:146
map @ array.js:289
_loadRecur @ ConfigManager.js:144
_loadIncludes @ ConfigManager.js:163
(anonymous) @ ConfigManager.js:62
getFinalConfig @ ConfigManager.js:78
(anonymous) @ Browser.js:2051
_milestoneFunction @ Browser.js:1992
loadConfig @ Browser.js:2049
(anonymous) @ Browser.js:168
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
13:35:07.705 xhr.js:267 XHR finished loading: GET "http://beta.sgc.loc:3000/jbrowse.conf".
xhr @ xhr.js:267
load @ JB_json_v1.js:45
(anonymous) @ ConfigManager.js:178
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:170
(anonymous) @ ConfigManager.js:146
map @ array.js:289
_loadRecur @ ConfigManager.js:144
_loadIncludes @ ConfigManager.js:163
(anonymous) @ ConfigManager.js:62
getFinalConfig @ ConfigManager.js:78
(anonymous) @ Browser.js:2051
_milestoneFunction @ Browser.js:1992
loadConfig @ Browser.js:2049
(anonymous) @ Browser.js:168
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
13:35:07.706 xhr.js:267 XHR finished loading: GET "http://beta.sgc.loc:3000/jbrowse_conf.json".
xhr @ xhr.js:267
load @ JB_json_v1.js:45
(anonymous) @ ConfigManager.js:178
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:170
(anonymous) @ ConfigManager.js:146
map @ array.js:289
_loadRecur @ ConfigManager.js:144
_loadIncludes @ ConfigManager.js:163
(anonymous) @ ConfigManager.js:62
getFinalConfig @ ConfigManager.js:78
(anonymous) @ Browser.js:2051
_milestoneFunction @ Browser.js:1992
loadConfig @ Browser.js:2049
(anonymous) @ Browser.js:168
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
13:35:07.735 GenomeView.js:62 >>> view constructor
13:35:08.190 xhr.js:267 XHR failed loading: GET "http://beta.sgc.loc:3000/data/names/root.json".
xhr @ xhr.js:267
Array.concat.dojo.xhr @ xhr.js:615
Array.concat.dojo.xhrGet @ xhr.js:643
constructor @ LazyTrie.js:66
(anonymous) @ declare.js:473
(anonymous) @ Browser.js:624
_milestoneFunction @ Browser.js:1992
loadNames @ Browser.js:598
(anonymous) @ Browser.js:178
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:328
notify @ Deferred.js:187
complete @ Deferred.js:168
resolve.callback @ Deferred.js:248
addResult @ DeferredList.js:54
(anonymous) @ DeferredList.js:37
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:358
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:589
finish @ lazyload.js:111
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
finish @ lazyload.js:113
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
css @ lazyload.js:365
_loadCSS @ Browser.js:589
(anonymous) @ Browser.js:352
forEach @ array.js:247
(anonymous) @ Browser.js:333
(anonymous) @ lang.js:385
contextRequire @ bootstrap 6bd6a93646d3ea06d82a:264
req @ bootstrap 6bd6a93646d3ea06d82a:158
(anonymous) @ Browser.js:330
_milestoneFunction @ Browser.js:1992
initPlugins @ Browser.js:276
(anonymous) @ Browser.js:177
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:2074
(anonymous) @ lang.js:385
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:68
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
signalListener @ Deferred.js:45
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:88
onLoad @ xhr.js:123
XMLHttpRequest.send (async)
xhr @ xhr.js:267
load @ JB_json_v1.js:45
(anonymous) @ ConfigManager.js:178
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:170
(anonymous) @ ConfigManager.js:146
map @ array.js:289
_loadRecur @ ConfigManager.js:144
_loadIncludes @ ConfigManager.js:163
(anonymous) @ ConfigManager.js:62
getFinalConfig @ ConfigManager.js:78
(anonymous) @ Browser.js:2051
_milestoneFunction @ Browser.js:1992
loadConfig @ Browser.js:2049
(anonymous) @ Browser.js:168
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
13:35:08.194 xhr.js:267 XHR finished loading: GET "http://beta.sgc.loc:3000/data/seq/refSeqs.json".
xhr @ xhr.js:267
(anonymous) @ Browser.js:536
_milestoneFunction @ Browser.js:1992
loadRefSeqs @ Browser.js:520
(anonymous) @ Browser.js:182
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
(anonymous) @ Browser.js:179
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:328
notify @ Deferred.js:187
complete @ Deferred.js:168
resolve.callback @ Deferred.js:248
addResult @ DeferredList.js:54
(anonymous) @ DeferredList.js:37
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:358
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:589
finish @ lazyload.js:111
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
finish @ lazyload.js:113
pollWebKit @ lazyload.js:326
setTimeout (async)
pollWebKit @ lazyload.js:335
load @ lazyload.js:247
css @ lazyload.js:365
_loadCSS @ Browser.js:589
(anonymous) @ Browser.js:352
forEach @ array.js:247
(anonymous) @ Browser.js:333
(anonymous) @ lang.js:385
contextRequire @ bootstrap 6bd6a93646d3ea06d82a:264
req @ bootstrap 6bd6a93646d3ea06d82a:158
(anonymous) @ Browser.js:330
_milestoneFunction @ Browser.js:1992
initPlugins @ Browser.js:276
(anonymous) @ Browser.js:177
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ Browser.js:2074
(anonymous) @ lang.js:385
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
(anonymous) @ all.js:68
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
signalListener @ Deferred.js:45
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
(anonymous) @ Deferred.js:70
signalListener @ Deferred.js:37
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:58
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
signalDeferred @ Deferred.js:81
signalListener @ Deferred.js:52
signalWaiting @ Deferred.js:28
Deferred.resolve @ Deferred.js:192
handleResponse @ xhr.js:88
onLoad @ xhr.js:123
XMLHttpRequest.send (async)
xhr @ xhr.js:267
load @ JB_json_v1.js:45
(anonymous) @ ConfigManager.js:178
signalListener @ Deferred.js:37
Deferred.then.promise.then @ Deferred.js:258
_loadInclude @ ConfigManager.js:170
(anonymous) @ ConfigManager.js:146
map @ array.js:289
_loadRecur @ ConfigManager.js:144
_loadIncludes @ ConfigManager.js:163
(anonymous) @ ConfigManager.js:62
getFinalConfig @ ConfigManager.js:78
(anonymous) @ Browser.js:2051
_milestoneFunction @ Browser.js:1992
loadConfig @ Browser.js:2049
(anonymous) @ Browser.js:168
callback @ ready.js:121
onEvent @ ready.js:47
processQ @ domReady.js:49
detectReady @ domReady.js:62
